name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Maven tests
      run: mvn --batch-mode --update-snapshots test

    - name: Maven package without test
      run: mvn --batch-mode --update-snapshots package -DskipTests

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jenkins-spring:$(date +%s)
